### ISSUE TITLE
Relocation to invalid address!

### ISSUE THREAD

**Issue by ghost** [devkitPro/3dstools#1]

**Comment by fincs** [comment]
Looks like this is the problematic relocation:

```
00391d20  0000032a R_ARM_PREL31      00387758   .ARM.extab
```

The address it is written to contains the value 0x80a8b0b0, which is quite weird.

**Comment by Steveice10** [comment]
Just did some further testing, it seems to be happening because I enabled C++ exceptions. Does 3dsxtool not support applications compiled with exceptions enabled?

**Comment by fincs** [comment]
It is supposed to, and it has worked before. However, this offset points to out of bounds data even in the original ELF. As I'm writing this I'm talking to a few people on IRC.
