### ISSUE TITLE
Troubleshooting Unaligned Relocation Error

### ISSUE THREAD

**Issue by pyroticinsanity** [devkitPro/3dstools#8]
I'm compiling a 3DS homebrew game and I'm getting "Unaligned Relocation" when it tries to build the .3dsx file from the .elf file. I'm able to build the .cia file and install it on the 3DS and it seems to run fine.

What is the reason for the tool failing with "Unaligned Relocation" and is there a way to troubleshoot what line of code is the problem?

Thanks!

**Comment by fincs** [comment]
What are you trying to build? It's hard to attempt to troubleshoot going completely blind...

**Comment by pyroticinsanity** [comment]
Sure. I was hoping there would be a more general solution. Right now I'm trying to port an SDL game called CSBWin: https://github.com/hackerb9/tachyon/tree/tachyon. I don't have my changes up yet but I'll get them up later today if that will help.

I was also talking with Ajenbo and MrHuu about DevilutionX as they are having the same issue and aren't sure how to solve the problem. Their repo is here: https://github.com/diasurgical/devilutionX/pull/483

**Comment by fincs** [comment]
To me it sounds like there are missing flags caused by not properly porting the projects' existing build system to our toolchain. For reference, the compiler flags set by our template makefiles are the following:

```makefile
ARCH	:=	-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft

CFLAGS	:=	-g -Wall -O2 -mword-relocations \
			-ffunction-sections \
			$(ARCH)

CFLAGS	+=	$(INCLUDE) -DARM11 -D_3DS
```

We provide a helper set of scripts (`pacman -S devkitpro-pkgbuild-helpers`) which automatically set the required environment variables such as CFLAGS or CC to the right values. They can be invoked by doing the following:

```bash
source /opt/devkitpro/3dsvars.sh
```

**Comment by pyroticinsanity** [comment]
Yep. I'm using the standard devkitpro Makefile from the examples. The one I'm using is basically a copy of this: https://github.com/pyroticinsanity/3dsdod/blob/master/Makefile.

I saw that there is a compiler option for telling the compiler to not use unaligned access but it doesn't seem to do anything either when I add it to the CFLAGS or CXXFLAGS: https://stackoverflow.com/questions/34951458/why-does-gcc-produce-illegal-unalign-accesses-for-arm-cortex-a9

One thing I noticed is there is a lot of pointer casts in the CSBWin code most likely due to reading data files so you see things like a u8* getting cast into a u32* to simplify access which could cause unaligned errors.

I saw this post where it mentions the ARM LDRD call is not unaligned safe so I'm wondering if the compiler is not factoring that in when generating the ELF file: https://www.alfonsobeato.net/arm/how-to-access-safely-unaligned-data/

**Comment by fincs** [comment]
"Unaligned relocation" doesn't mean that you have unaligned data access, it means that there is a static pointer needing relocation, at an unaligned address. I don't know why your program is generating misaligned pointers to data.

**Comment by pyroticinsanity** [comment]
When you say "static pointer" are you referring to a static block of data that has an unaligned starting address (e.g. static int textBlock[8000];" or is it a pointer to a block of data (e.g. static int* textBlockPtr = &textBlock[1];", or something else entirely?

I've uploaded my changes to a github branch here if you want to see what I'm working with. It compiles the .elf file but fails when generating the 3dsx: https://github.com/pyroticinsanity/tachyon/tree/3ds_port

Is there any way to reverse engineer from 3dsxtool where the relocation is coming from into an object file and offset to help narrow down the issue?

**Comment by pyroticinsanity** [comment]
I think I'm getting a little further. I compiled the 3dsxtool to also print out the address that it is on and it shows up as "0x2014aa". Using readelf I see that it is looking at this symbol:
 6718: 002014a8    70 OBJECT  GLOBAL DEFAULT   10 s12406

Which is here: https://github.com/pyroticinsanity/tachyon/blob/102536a35df228f594e16c2dcb5ff7f2c5149f24/Chaos.cpp#L607

If I change the dlgButton_12610 pointers to NULL then it fails at another DlgButton pointer here: https://github.com/pyroticinsanity/tachyon/blob/102536a35df228f594e16c2dcb5ff7f2c5149f24/Chaos.cpp#L615

I looked at the struct here: https://github.com/pyroticinsanity/tachyon/blob/102536a35df228f594e16c2dcb5ff7f2c5149f24/Chaos.cpp#L83 and it looks like it should be memory aligned.

The only other thing I can see is that the arrays that the pointers are pointing to have an odd number of elements to them but that doesn't seem like it should be a problem.

Any thoughts on what else I can look into?

**Comment by fincs** [comment]
Your structs are packed for some reason, hence why the pointer member of your struct is a misaligned address: https://github.com/pyroticinsanity/tachyon/blob/master/Chaos.cpp#L59

Relocations at misaligned addresses are not supported by the 3dsx format. Either remove the packing (i.e. remove that line I linked to), or manually add two bytes of padding prior to the member: https://github.com/pyroticinsanity/tachyon/blob/master/Chaos.cpp#L96

**Comment by pyroticinsanity** [comment]
Nice catch! I wasn't aware of that compiler feature.

I commented the pragma out in all the code and it builds the 3dsx file. I'm not sure why the original author had that in there though. Do you know if there are any repercussions from changing it to unpacked?

**Comment by AJenbo** [comment]
For Diablo, it was done to keep down the size of network traffic and save game files, so changing that could break savegame and multiplayer compatibility. But the problematic one was TSFX, which isn't part of either, so maybe they were just trying to save on memory footprint.

**Comment by fincs** [comment]
Alright, so I deem this solved.

**Comment by MrHuu** [comment]
Much appreciated, thanks!
This will actually help with some other projects i had going as-well.
